<?php
// Auto-generated by CI/CD. DO NOT EDIT MANUALLY.
return [
    'version'     => '2026.07.21',
    'data_date'   => '2026-07-21',
    'source_hash' => '5d8a870a71da-ba8497156c5c',
    'generated_at' => '2026-07-21T04:58:29+00:00',
    'sources'     => [
        'wilayah' => [
            'repo' => 'cahyadsn/wilayah',
            'branch' => 'master',
            'hash' => '5d8a870a71daaee0c7db4f3d9767de0355713cae',
        ],
        'wilayah_kodepos' => [
            'repo' => 'cahyadsn/wilayah_kodepos',
            'branch' => 'main',
            'hash' => 'ba8497156c5cc9bcbfc527f7b8875d403eda2354',
        ],
    ],
    'counts'      => [
        'provinces' => 38,
        'regencies' => 514,
        'districts' => 7265,
        'villages'  => 83345,
    ],
];
