<?php
// Auto-generated by CI/CD. DO NOT EDIT MANUALLY.
return [
    'version'     => '2026.07.23',
    'data_date'   => '2026-07-23',
    'source_hash' => 'c3dda29f64fe-ba8497156c5c',
    'generated_at' => '2026-07-23T05:15:39+00:00',
    'sources'     => [
        'wilayah' => [
            'repo' => 'cahyadsn/wilayah',
            'branch' => 'master',
            'hash' => 'c3dda29f64fed36777b2b776c5a2e9b0fbba5d97',
        ],
        'wilayah_kodepos' => [
            'repo' => 'cahyadsn/wilayah_kodepos',
            'branch' => 'main',
            'hash' => 'ba8497156c5cc9bcbfc527f7b8875d403eda2354',
        ],
    ],
    'counts'      => [
        'provinces' => 38,
        'regencies' => 514,
        'districts' => 7265,
        'villages'  => 83345,
    ],
];
