<?php
// Auto-generated by CI/CD. DO NOT EDIT MANUALLY.
return [
    'version'     => '2026.07.02',
    'data_date'   => '2026-07-02',
    'source_hash' => 'b8524cf04c54-4fa8c592a581',
    'generated_at' => '2026-07-02T05:48:58+00:00',
    'sources'     => [
        'wilayah' => [
            'repo' => 'cahyadsn/wilayah',
            'branch' => 'master',
            'hash' => 'b8524cf04c547488a44e540a2a78c59765c1bbfb',
        ],
        'wilayah_kodepos' => [
            'repo' => 'cahyadsn/wilayah_kodepos',
            'branch' => 'main',
            'hash' => '4fa8c592a581bf2fc4fb0a373010000c5bac6251',
        ],
    ],
    'counts'      => [
        'provinces' => 38,
        'regencies' => 514,
        'districts' => 7265,
        'villages'  => 83345,
    ],
];
